# Generated by Django 5.0.1 on 2024-01-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth_app', '0002_patientprofile_address_line1_patientprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
